import { Campaign, Store, Voucher } from "./types";

export const DEFAULT_STORES: Store[] = [
  {
    id: "store-sai-01",
    name: "Sai Enterprises - Flagship Tech World (MG Road)",
    city: "Bengaluru",
    address: "42, Commercial Plaza, MG Road",
    code: "SAI-MG-01",
  },
  {
    id: "store-sai-02",
    name: "Sai Enterprises - Gadget Zone (Indiranagar)",
    city: "Bengaluru",
    address: "100ft Road, Opp. Metro Pillar 48, Indiranagar",
    code: "SAI-IND-02",
  },
  {
    id: "store-sai-03",
    name: "Sai Enterprises - Smart Experience (HSR Layout)",
    city: "Bengaluru",
    address: "27th Main, Sector 1, HSR Layout",
    code: "SAI-HSR-03",
  },
];

export const DEFAULT_CAMPAIGN: Campaign = {
  id: "camp-sai-500",
  name: "Sai Enterprises ₹500 In-Store Gadget Reward",
  headline: "Get ₹500 OFF Your Next Gadget",
  subheadline:
    "Complete 2 quick steps and unlock an instant ₹500 voucher on Smartphones, Audio, Smartwatches & Premium Accessories.",
  rewardAmount: 500,
  minOrderValue: 999,
  validDays: 14,
  validFrom: "2026-09-01T00:00:00Z",
  validTo: "2026-10-31T23:59:59Z",
  terms: [
    "Valid at all Sai Enterprises physical stores across Bangalore.",
    "Applicable on Smartphones, Smartwatches, Earbuds, Chargers, and Premium Accessories.",
    "Minimum purchase value of ₹999 required to redeem the ₹500 voucher.",
    "Limit one ₹500 voucher per mobile number during the campaign window.",
    "Valid for 14 days from date of generation. Cannot be clubbed with wholesale bulk clearance.",
  ],
  reviewUrl: "https://g.page/r/sai-enterprises-gadgets/review",
  reviewPlatform: "Google Reviews",
  socialLinks: {
    instagram: "https://www.instagram.com/saikeshav.ent/",
    youtube: "https://youtube.com/@saikeshav_enterprises",
    facebook: "https://www.facebook.com/profile.php?id=61592129150557",
    website: "https://www.facebook.com/share/1J1GDYGkxs/?mibextid=wwXIfr",
    menuUrl: "https://www.instagram.com/saikeshav.ent?stkn=ZnFodWh3N3FnMHVn&utm_source=qr",
    whatsapp: "https://whatsapp.com/channel/0029VbDIQjDI7BeF7j3TDx45",
    facebookPage: "https://www.facebook.com/share/1J1GDYGkxs/?mibextid=wwXIfr",
  },
  enabledStores: ["store-sai-01", "store-sai-02", "store-sai-03"],
  otpRequired: false,
  dailyCapPerStore: 150,
  googleSheetUrl: "https://docs.google.com/spreadsheets/d/1F8t-XiG6khQjM8ql6IjqJUImKUnfCdQc1hVn77OTMSg/edit?usp=sharing",
  googleSheetWebhookUrl: "https://script.google.com/macros/s/AKfycbwiJihWJtE2YVaUejBTpxsVzmNT2Qqw2NPvIzlOzhGlsIUSDHqshjAydP2gI28cjfzZ/exec",
  isActive: true,
};

export const INITIAL_VOUCHERS: Voucher[] = [
  {
    id: "vch-sai-1001",
    code: "SAI500-8X4K2P",
    campaignId: "camp-sai-500",
    customerId: "cust-9876500001",
    phone: "9876500001",
    storeId: "store-sai-01",
    value: 500,
    minOrderValue: 999,
    status: "REDEEMED",
    issuedAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    expiresAt: new Date(Date.now() + 86400000 * 13).toISOString(),
    redeemedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    redeemedStoreId: "store-sai-01",
    posOrderRef: "BILL-SAI-9921",
  },
  {
    id: "vch-sai-1002",
    code: "SAI500-3L9M7V",
    campaignId: "camp-sai-500",
    customerId: "cust-9876500002",
    phone: "9876500002",
    storeId: "store-sai-02",
    value: 500,
    minOrderValue: 999,
    status: "ACTIVE",
    issuedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    expiresAt: new Date(Date.now() + 86400000 * 14).toISOString(),
  },
  {
    id: "vch-sai-1003",
    code: "SAI500-5T2W9Q",
    campaignId: "camp-sai-500",
    customerId: "cust-9876500003",
    phone: "9876500003",
    storeId: "store-sai-01",
    value: 500,
    minOrderValue: 999,
    status: "ACTIVE",
    issuedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    expiresAt: new Date(Date.now() + 86400000 * 14).toISOString(),
  },
];
